### ISSUE TITLE
Problem on run in Docker

### ISSUE THREAD

**Issue by yanboyang713** [pacman-repo-builder/pacman-repo-builder#54]
Hello @KSXGitHub ,

Good day to you.

I faced a problem with running in Docker.

Currently, I am using **tmacro/pacman-repo-builder** image from Docker Hub.
Is this your image?

I could NOT download those required packages from those Arch Mirrors.
Could you share your DockerFile with me? Thanks

How did you run [pacman-repo-builder](https://github.com/pacman-repo-builder/pacman-repo-builder) in **Docker** now?

Thanks for your time,
Boyang Yan
```
 Total (10/52)                                                                                       19.7 MiB  23.7 MiB/s 00:01 [#############################################################################] 100%
error: failed retrieving file 'python-pip-22.1.2-1-any.pkg.tar.zst' from geo.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'xorgproto-2022.1-1-any.pkg.tar.zst' from geo.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-docutils-1:0.19-1-any.pkg.tar.zst' from geo.mirror.pkgbuild.com : The requested URL returned error: 404
warning: too many errors from geo.mirror.pkgbuild.com, skipping for the remainder of this transaction
error: failed retrieving file 'python-setuptools-1:61.3.1-1-any.pkg.tar.zst' from geo.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-3.10.5-1-x86_64.pkg.tar.zst' from geo.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-pygments-2.12.0-1-any.pkg.tar.zst' from geo.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-cryptography-37.0.4-1-x86_64.pkg.tar.zst' from geo.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-pip-22.1.2-1-any.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'xorgproto-2022.1-1-any.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'python-docutils-1:0.19-1-any.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
warning: too many errors from mirror.rackspace.com, skipping for the remainder of this transaction
error: failed retrieving file 'python-setuptools-1:61.3.1-1-any.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'python-3.10.5-1-x86_64.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'python-pygments-2.12.0-1-any.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'python-cryptography-37.0.4-1-x86_64.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'python-pip-22.1.2-1-any.pkg.tar.zst' from mirror.leaseweb.net : The requested URL returned error: 404
error: failed retrieving file 'python-pygments-2.12.0-1-any.pkg.tar.zst' from mirror.leaseweb.net : The requested URL returned error: 404
error: failed retrieving file 'python-cryptography-37.0.4-1-x86_64.pkg.tar.zst' from mirror.leaseweb.net : The requested URL returned error: 404
warning: too many errors from mirror.leaseweb.net, skipping for the remainder of this transaction
error: failed retrieving file 'xorgproto-2022.1-1-any.pkg.tar.zst' from mirror.leaseweb.net : The requested URL returned error: 404
error: failed retrieving file 'python-docutils-1:0.19-1-any.pkg.tar.zst' from mirror.leaseweb.net : The requested URL returned error: 404
error: failed retrieving file 'python-setuptools-1:61.3.1-1-any.pkg.tar.zst' from mirror.leaseweb.net : The requested URL returned error: 404
error: failed retrieving file 'python-3.10.5-1-x86_64.pkg.tar.zst' from mirror.leaseweb.net : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
```

**Comment by KSXGitHub** [comment]
> Currently, I am using **tmacro/pacman-repo-builder** image from Docker Hub.
> Is this your image?

It's not.

The only official image is the github action: https://github.com/pacman-repo-builder/action

**Comment by yanboyang713** [comment]
@KSXGitHub 
Thanks. 
Do you know how to create an empty meta-scientific-linux.db to my repo? Using repo-add?
error: failed retrieving file 'meta-scientific-linux.db' from raw.github.com : The requested URL returned error: 404

**Comment by yanboyang713** [comment]
@KSXGitHub 
Currently, pending on the below step.
```
- name: Build pacman packages
        uses: pacman-repo-builder/action@0.0.0-rc.62
        with:
          command: |
            set -o errexit -o pipefail -o nounset
            (
              echo ''
              echo '[meta-scientific-linux]'
              echo 'SigLevel = Optional'
              echo 'Server = https://raw.github.com/yanboyang713/Meta-Scientific-repository/main/repo'
            ) >> /etc/pacman.conf
            pacman -Sy
            build-pacman-repo build
```

**Comment by KSXGitHub** [comment]
You are not using this tool the right way.

You wanted to create `meta-scientific-linux`, yes? Adding this repo to `/etc/pacman.conf` is unnecessary. What your CI should do instead is to use `git` to clone the repo, then use the action to build the packages, and then use `git` to commit the changes, and finally use `git` to push the changes.

Example: https://github.com/KSXGitHub/personal-crates/blob/4b2682e480cea5a7c6757bb4c7ae694fa062bbcc/.github/workflows/build.yaml#L53-L83 

Adding `[meta-scientific-linux]` entry to your `/etc/pacman.conf` is only necessary when you need to consume your own packages (i.e. when you need to `pacman -S` your own packages).

**Comment by yanboyang713** [comment]
Thanks @KSXGitHub ,

On Upload packages, I faced this error. Do yo know the reason why? Thanks

This is my CI/CD action, same with you. 
https://github.com/yanboyang713/Meta-Scientific-Collection-PKGBUILDs/blob/main/.github/workflows/build.yaml

```
Current branch main is up to date.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/yanboyang713/Meta-Scientific-repository.git/'
Error: Process completed with exit code 128.
```

Have you tried using SSH deploy key for push to another repository?
Like: https://cpina.github.io/push-to-another-repository-docs/setup-using-ssh-deploy-keys.html#setup-ssh-deploy-keys

Thanks

**Comment by KSXGitHub** [comment]
Setting up git credentials is outside the scope of this action, but I'll try to help nonetheless.

You may setup the `git push` step however you like, be it username/password or SSH deployment. This tool does not concern with deployment.

In my CI, the `AUTH_PASSWORD` isn't my GitHub password, it is a GitHub token with push permission.

SSH deployment does look simpler on the CI side, but you know what they say: If it ain't broke, don't fix it. So I have no reason to change for the sake of change.

**Comment by KSXGitHub** [comment]
Also, when copy-pasting GitHub token, be careful of **trailing newline**. It was probably the reason for your error

**Comment by yanboyang713** [comment]
Thanks @KSXGitHub 

All well done.
