### ISSUE TITLE
PKGBUILD users management

### ISSUE THREAD

**Issue by yanboyang713** [pacman-repo-builder/pacman-repo-builder#56]
Hello @KSXGitHub ,

May I ask a question about PKGBUILD user management?

When I write the .install script, I want to know the current user's username.

For example,
My username is yanboyang; I am installing a package (named A). How could package A's .install script could get my username yanboyang?

Have a nice day,
Boyang Y

**Comment by KSXGitHub** [comment]
Whose username? What purpose does this serve?

A PKGBUILD shouldn't be environment dependent. It should be the same for all users.

BTW, this question of yours is way outside of the scope of `pacman-repo-builder`. I suggest you should bring this type of question to an Arch Linux forum instead.

**Comment by yanboyang713** [comment]
ok, thanks for your help.

Some of my Dotfiles need to be put to user dir.
