### ISSUE TITLE
strange issue: use makepkg -si build and run successfuly, but pacman-repo-builder fails

### ISSUE THREAD

**Issue by yanboyang713** [pacman-repo-builder/pacman-repo-builder#57]
Hello @KSXGitHub ,

Good day to you.

Today, I found a strange issue. If I use **makepkg -si** build locally, it could build and run successfully, but when I use, **pacman-repo-builder** fails.

My PKGBUILD file is at the link below.
https://github.com/yanboyang713/Meta-Scientific-Collection-PKGBUILDs/blob/main/members/meta-wm/PKGBUILD

Do you know the reason?

Have a nice day, and thanks for your help.
Boyang Yan

**Comment by KSXGitHub** [comment]
What is the error message?

**Comment by yanboyang713** [comment]
Hello @KSXGitHub,

Thanks for your reply,

The ERROR MSG shows **warning: dependency cycle detected**

My depends below. Do you know why this happened?

```
depends=('picom' 'feh' 'acpi' 'rofi' 'pavucontrol' 'zsh' 'imlib2' 'xorg-xsetroot' 'wget' 'xorg-server' 'alsa-utils' 'xorg-xbacklight' 'nerd-fonts-jetbrains-mono')
```

'''
warning: dependency cycle detected:

Packages (143) acpi-1.7-3  adobe-source-code-pro-fonts-2.038ro+1.058it+1.018var-1  adwaita-icon-theme-43-1  alsa-lib-1.2.8-1  alsa-topology-conf-1.2.5.1-1  alsa-ucm-conf-1.2.8-1  alsa-utils-1.2.8-1  at-spi2-core-2.46.0-2  atkmm-2.28.3-1  avahi-0.8+22+gfd482a7-3  cairo-1.17.6-2  cairomm-1.14.4-1  cantarell-fonts-1:0.303.1-1  dconf-0.40.0-2  desktop-file-utils-0.26-2  duktape-2.7.0-4  feh-3.9.1-2  flac-1.4.2-1  fontconfig-2:2.14.1-2  freetype2-2.12.1-1  fribidi-1.0.12-1  gdk-pixbuf2-2.42.10-1  giflib-5.2.1-2  glib-networking-1:2.74.0-1  glibmm-2.66.5-1  graphite-1:1.3.14-2  gsettings-desktop-schemas-43.0-1  gtk-update-icon-cache-1:4.8.2-1  gtk3-1:3.24.35-2  gtkmm3-3.24.7-1  harfbuzz-5.3.1-3  hicolor-icon-theme-0.17-2  imlib2-1.9.1-2  iso-codes-4.12.0-1  json-glib-1.6.6-2  lcms2-2.14-1  libasyncns-1:0.8+r3+g68cd5af-2  libcanberra-1:0.30+r2+gc0620e4-2  libcloudproviders-0.3.1+r8+g3a229ee-1  libcolord-1.4.6-1  libconfig-1.7.3-1  libcups-1:2.4.2-3  libdaemon-0.14-5  libdatrie-0.2.13-2  libdrm-2.4.114-1  libedit-20210910_3.1-2  libepoxy-1.5.10-1  libev-4.33-2  libevdev-1.13.0-1  libexif-0.6.24-1  libfontenc-1.1.6-1  libglvnd-1.5.0-1  libgudev-237-2  libice-1.0.10-4  libinput-1.22.0-1  libjpeg-turbo-2.1.4-2  libogg-1.3.5-1  libomxil-bellagio-0.9.3-3  libpciaccess-0.17-1  libpng-1.6.39-1  libproxy-0.4.18-1  libpulse-16.1-3  librsvg-2:2.55.1-1  libsamplerate-0.2.2-1  libsigc++-2.10.8-1  libsm-1.2.3-3  libsndfile-1.1.0-3  libsoup3-3.2.2-1  libstemmer-2.2.0-2  libthai-0.1.29-2  libtiff-4.4.0-4  libunwind-1.6.2-2  libusb-1.0.26-1  libvorbis-1.3.7-3  libwacom-2.5.0-1  libx11-1.8.2-2  libxau-1.0.10-2  libxcb-1.15-2  libxcomposite-0.4.5-4  libxcursor-1.2.1-2  libxcvt-0.1.2-1  libxdamage-1.1.5-5  libxdg-basedir-1.2.3-1  libxdmcp-1.1.4-1  libxext-1.3.5-1  libxfixes-6.0.0-2  libxfont2-2.0.6-1  libxft-2.3.7-1  libxi-1.8-2  libxinerama-1.1.5-1  libxkbcommon-1.4.1-2  libxkbcommon-x11-1.4.1-2  libxkbfile-1.1.1-1  libxmu-1.1.4-1  libxrandr-1.5.3-1  libxrender-0.9.11-1  libxshmfence-1.3.1-1  libxt-1.2.1-1  libxtst-1.2.4-1  libxxf86vm-1.1.5-1  llvm-libs-14.0.6-4  lm_sensors-1:3.6.0.r41.g31d1f125-2  lzo-2.10-4  mesa-22.2.3-1  mtdev-1.1.6-2  opus-1.3.1-3  pango-1:1.50.12-1  pangomm-2.46.3-1  pavucontrol-1:5.0+r[61](https://github.com/yanboyang713/Meta-Scientific-Collection-PKGBUILDs/actions/runs/3586149246/jobs/6034997085#step:7:62)+gee77d86-2  pcre-8.45-3  picom-10.1-1  pixman-0.42.2-1  rofi-1.7.5-1  shared-mime-info-2.0+155+gf4e7cbc-1  sound-theme-freedesktop-0.8-5  speex-1.2.1-1  speexdsp-1.2.1-1  startup-notification-0.12-7  tdb-1.4.7-1  tracker3-3.4.1-1  vulkan-icd-loader-1.3.235-1  wayland-1.21.0-1  wget-1.21.3-1  xcb-proto-1.15.2-2  xcb-util-0.4.0-4  xcb-util-cursor-0.1.4-1  xcb-util-image-0.4.1-2  xcb-util-renderutil-0.3.10-1  xcb-util-wm-0.4.2-1  xcb-util-xrm-1.3-2  xf86-input-libinput-1.2.1-1  xkeyboard-config-2.37-1  xorg-fonts-encodings-1.0.6-1  xorg-server-21.1.4-1  xorg-server-common-21.1.4-1  xorg-setxkbmap-1.3.3-1  xorg-xbacklight-1.2.3-3  xorg-xkbcomp-1.4.5-1  xorg-xrandr-1.5.1-2  xorg-xsetroot-1.1.3-1  xorgproto-2022.2-1  zsh-5.9-1  meta-wm-0.4-1

warning: mesa will be installed before its libglvnd dependency
warning: dependency cycle detected:
warning: harfbuzz will be installed before its freetype2 dependency

installing xorg-server...
>>> xorg-server has now the ability to run without root rights with
    the help of systemd-logind. xserver will fail to run if not launched
    from the same virtual terminal as was used to log in.
    Without root rights, log files will be in ~/.local/share/xorg/ directory.

    Old behavior can be restored through Xorg.wrap config file.
    See Xorg.wrap man page (man xorg.wrap).
'''

**Comment by KSXGitHub** [comment]
That wasn't error message. Just a few warnings. It seems that it was successful.

**Comment by yanboyang713** [comment]
@KSXGitHub Yes, those are **warnings**. But, when I install my package, it will fail.

If I use **makepkg -si** build locally, it could build and run successfully based on the same PKGBUILD.

**Comment by KSXGitHub** [comment]
Can you run `pacman -Sy`, `pacman -Ss meta-wm`, and `pacman -Si meta-wm` and tell me the result?

**Comment by yanboyang713** [comment]
@KSXGitHub 

```
sudo pacman -Sy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archlinuxcn is up to date
 meta-scientific                                                                       2.4 KiB  6.46 KiB/s 00:00 [####################################################################] 100%
```
```
sudo pacman -Ss meta-wm
meta-scientific/meta-wm 0.5-1
    Meta-WM's version of ChadWM (DWM Modif)
```

```
sudo pacman -Si meta-wm
Repository      : meta-scientific
Name            : meta-wm
Version         : 0.5-1
Description     : Meta-WM's version of ChadWM (DWM Modif)
Architecture    : x86_64
URL             : https://github.com/yanboyang713/meta-wm.git
Licenses        : MIT
Groups          : None
Provides        : dwm
Depends On      : picom  feh  acpi  rofi  pavucontrol  zsh  imlib2  xorg-xsetroot  wget  xorg-server  alsa-utils  nerd-fonts-jetbrains-mono
Optional Deps   : None
Conflicts With  : dwm
Replaces        : None
Download Size   : 1717.17 KiB
Installed Size  : 11620.49 KiB
Packager        : Boyang Yan <yanboyang713@gmail.com>
Build Date      : Thu 01 Dec 2022 08:56:31
Validated By    : MD5 Sum  SHA-256 Sum
```

**Comment by KSXGitHub** [comment]
No problem so far. Now run `sudo pacman -S meta-wm`. If it succeed, then we know that it was a user error (you forgetting to run `pacman -Sy` before install).

**Comment by yanboyang713** [comment]
@KSXGitHub no, I am **not** forget to run **pacman -Sy** before install.

**sudo pacman -S meta-wm** meta-wm could NOT works.

only **makepkg -si** coud works.

**Comment by yanboyang713** [comment]
I don't know what's the difference between makepkg -si and sudo pacman -S meta-wm

**Comment by KSXGitHub** [comment]
Weird, `pacman -Si` can fetch info from the database means that the package is already built.

What is the error message of `sudo pacman -S meta-wm`?

**Comment by yanboyang713** [comment]
@KSXGitHub 
When I run **sudo pacman -S meta-wm**, no any **error message** shows out.

So, very strange issue

**Comment by KSXGitHub** [comment]
> no any **error message** shows out.

which means it already installed!

If you want to double check, just run `pacman -Q meta-wm` (no needs for `sudo`).

BTW, `pacman -Ss` and `pacman -Si` don't need `sudo` either, because they merely query the database. Don't just blindly add `sudo` everywhere lest you create security issues.

**Comment by yanboyang713** [comment]
@KSXGitHub 
Yes, it has already been installed successfully.

But, just could **not** work like **makepkg -si**

**Comment by yanboyang713** [comment]
@KSXGitHub Do you think some of my **pacman-repo-builder** settings may impact this issue?

```
global-settings:
  container: members
  repository: Meta-Scientific-repository/repo/meta-scientific.db.tar.gz
  dereference-database-symlinks: true
  clean-after-build: false
  packager: 'Boyang Yan <yanboyang713@gmail.com>'
  check: enabled
  allow-failure: false
  install-missing-dependencies: true
  arch-filter: [x86_64]
```

**Comment by KSXGitHub** [comment]
> But, just could **not** work like **makepkg -si**

What do you mean?

In any case, `meta-wm 0.5-1` already present in your database, which means pacman-repo-builder succeeded, which means I can't help you with your problems now.

It is possible that your PKGBUILD or your Makefile depends on the environment it was running on (bad practice, btw).

Anyway, this sort of questions are better fit on Arch Linux forums. Please don't expect me, a maintainer, to be your tech support.

**Comment by yanboyang713** [comment]
Hello @KSXGitHub,

Thanks for your help.

yes, seen my **Makefile** may depends on the environment.

Thanks for your time
