### ISSUE TITLE
error while loading shared libraries: `libalpm.so.14`

### ISSUE THREAD

**Issue by ReenigneArcher** [pacman-repo-builder/pacman-repo-builder#63]
`build-pacman-repo <any arg>` command fails with the following error

```
build-pacman-repo: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory
```

This occurs inside of the `archlinux/archlinux:base-devel` container image.

Here is my workflow. https://github.com/LizardByte/pacman-repo/blob/87ad23ec044c0675f431ec09609d60d0090a2fdf/.github/workflows/build-repo.yml#L58

I guess `pacman` was updated and no longer provides `libalpm.so.14`: https://archlinux.org/packages/core/x86_64/pacman/

**Comment by KSXGitHub** [comment]
I'm very busy at the moment. While waiting for me to eventually resolve this issue, you can fork this repo, update all dependencies in `Cargo.toml` (or at least `alpm` and `git2`), remove unnecessary steps from `.github/workflows/deploy.yaml`, and then produce your own release artifacts with GitHub CI.

**Comment by ReenigneArcher** [comment]
I'm not familiar with cargo, but I'll take a look.

It looks like this repo used to have `renovate-bot` configured. Would you accept a PR that adds `dependabot`? It can take care of cargo dep updates.

**Comment by KSXGitHub** [comment]
> Would you accept a PR that adds `dependabot`? It can take care of cargo dep updates.

This repo already has dependabot configured. See `.github/dependabot.yml`.

**Comment by ReenigneArcher** [comment]
Oh, I see that... I wonder why it's not firing

**Comment by KSXGitHub** [comment]
Instead of relying on dependabot, you can update it yourself.

```sh
# update just alpm
cargo update --breaking alpm

# update all dependencies
cargo update
```

If the above commands fail, you may edit `Cargo.toml` manually: replace `alpm = "^3.0.5"` with `alpm = "^4.0.1"`. Then run `cargo build --release`.

**Comment by ReenigneArcher** [comment]
Sorry, I'm having no luck with this repo.

Had trouble checking it out on Windows due to these two files, with colon's in the name.

- `tests/fixtures/outdated/__template__/repo/out-of-date-by-epoch-1:-1.2.3-1-any.pkg.tar.zst`
- `tests/fixtures/outdated/__template__/repo/out-of-date-by-epoch-2:-1.2.3-1-any.pkg.tar.zst`

Thought I could ignore those files, and made all the changes... but git won't allow me to create a commit.

**Comment by KSXGitHub** [comment]
> Had trouble checking it out on Windows due to these two files

You don't have Arch Linux? This repo only builds on Arch.

Anyway, if you have Windows, try installing Arch Linux WSL and then start from there.

~~Another simpler way is too simply remove these files and the tests that need them, unless you intent to maintain the fork for a long term.~~ (probably doesn't work, it still requires libalpm)

**Comment by ReenigneArcher** [comment]
No, I don't normally use Linux except in CI, or dev environments. But I do support Linux for my repos.

I'll submit a PR to try fixing the dependabot errors, as I can do that through GitHub UI somewhat easily.

**Comment by KSXGitHub** [comment]
I think set up a dev environment should be quicker for you. Who know what other BS an attempt with dependabot or similar services will lead to.
